# Build stage
FROM registry.redhat.io/ubi9/go-toolset:9.8-1791479310@sha256:6f246e8913d082df463b62a74c72f0d2b410583e1b2ac48add39cd7ede59ce62 AS builder

USER root
WORKDIR /app

COPY . .

ENV CGO_ENABLED=1
ENV GOFIPS140=v1.0.0

RUN go mod edit -godebug=fips140=auto
RUN go mod vendor
RUN go build -buildvcs=false -tags=no_openssl -o tufcli .

FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:5858f9ace07316e3b12caab62f6c2481a5030bb6bafdca5a9ea324c321ef36df AS deploy

COPY --from=builder /app/tufcli /usr/bin/

COPY rhtas/tuf-repo-init.sh /usr/bin/

ENTRYPOINT ["/usr/bin/tuf-repo-init.sh"]
USER 1001

LABEL description="tufcli-init is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.description="tufcli-init is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.display-name="tufcli-init container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="tufcli-init Trusted Artifact Signer"
LABEL summary="Provides the tuf-repo-init script for generating an initial trust root for RHTAS"
LABEL com.redhat.component="tufcli-init"
LABEL name="rhtas/tufcli-init-rhel9"
