# Build stage
FROM registry.redhat.io/ubi9/go-toolset:9.8-1788409979@sha256:5e68f09a652ac6627a83c57655e42e24575efb278b54336039c9308607fc6b21 AS builder

USER root
WORKDIR /app

COPY . .

ENV CGO_ENABLED=1
ENV GOFIPS140=v1.0.0

RUN cp -r hack/pcsc-lite/PCSC /usr/include/PCSC && \
    cp hack/pcsc-lite/libpcsclite.pc /usr/lib64/pkgconfig/libpcsclite.pc && \
    gcc -shared -o /usr/lib64/libpcsclite.so.1 hack/pcsc-lite/pcsc_stub.c -Wl,-soname,libpcsclite.so.1 && \
    ln -sf libpcsclite.so.1 /usr/lib64/libpcsclite.so
RUN go mod edit -godebug=fips140=auto
RUN go mod vendor
RUN go build -buildvcs=false -tags=no_openssl,piv -o tufcli .

# Final stage
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93

COPY --from=builder /app/tufcli /tufcli
COPY --from=builder /usr/lib64/libpcsclite.so.1 /usr/lib64/libpcsclite.so.1
COPY LICENSE /licenses/LICENSE

LABEL description="tufcli is a Go command-line utility for generating and signing TUF repositories"
LABEL io.k8s.description="tufcli is a Go command-line utility for generating and signing TUF repositories"
LABEL io.k8s.display-name="tufcli container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="tufcli Trusted Artifact Signer"
LABEL summary="Provides the tufcli binary for generating and signing TUF repositories"
LABEL com.redhat.component="tufcli"
LABEL name="rhtas/tufcli-rhel9"

USER 65532:65532

#ENTRYPOINT
ENTRYPOINT ["/tufcli"]
