# Build stage
FROM registry.redhat.io/ubi9/go-toolset:9.8-1789040808@sha256:685ccca486cc2c82b0818d835abecb1aed7a396e76ba416cfc47c28067f5d365 AS builder

USER root
WORKDIR /app

COPY . .

ENV CGO_ENABLED=1
ENV GOFIPS140=v1.0.0

RUN cp -r hack/pcsc-lite/PCSC /usr/include/PCSC && \
    cp hack/pcsc-lite/libpcsclite.pc /usr/lib64/pkgconfig/libpcsclite.pc && \
    gcc -c -o /tmp/pcsc_stub.o hack/pcsc-lite/pcsc_stub.c && \
    ar rcs /usr/lib64/libpcsclite.a /tmp/pcsc_stub.o && rm /tmp/pcsc_stub.o
RUN go mod edit -godebug=fips140=auto
RUN go mod vendor
RUN go build -buildvcs=false -tags=no_openssl,piv -o tufcli .

# Final stage
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae

COPY --from=builder /app/tufcli /tufcli
COPY LICENSE /licenses/LICENSE

LABEL description="tufcli is a Go command-line utility for generating and signing TUF repositories"
LABEL io.k8s.description="tufcli is a Go command-line utility for generating and signing TUF repositories"
LABEL io.k8s.display-name="tufcli container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="tufcli Trusted Artifact Signer"
LABEL summary="Provides the tufcli binary for generating and signing TUF repositories"
LABEL com.redhat.component="tufcli"
LABEL name="rhtas/tufcli-rhel9"

USER 65532:65532

#ENTRYPOINT
ENTRYPOINT ["/tufcli"]
