# Build stage
FROM registry.redhat.io/ubi9/go-toolset:9.8-1789040808@sha256:685ccca486cc2c82b0818d835abecb1aed7a396e76ba416cfc47c28067f5d365 AS builder

USER root
WORKDIR /app

COPY . .

ENV CGO_ENABLED=1
ENV GOFIPS140=v1.0.0

RUN go mod edit -godebug=fips140=auto
RUN go mod vendor
RUN go build -buildvcs=false -tags=no_openssl -o tufcli .

FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:206b65b8ee0f04b992818c9a51b29081b14974630d4850bc358097d0c44ea156 AS deploy

COPY --from=builder /app/tufcli /usr/bin/

COPY rhtas/tuf-repo-init.sh /usr/bin/

ENTRYPOINT ["/usr/bin/tuf-repo-init.sh"]
USER 1001

LABEL description="tufcli-init is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.description="tufcli-init is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.display-name="tufcli-init container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="tufcli-init Trusted Artifact Signer"
LABEL summary="Provides the tuf-repo-init script for generating an initial trust root for RHTAS"
LABEL com.redhat.component="tufcli-init"
LABEL name="rhtas/tufcli-init-rhel9"
