apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/tufcli?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "main" &&
      (
        "Dockerfile.cli-stack.rh".pathChanged() ||
        ".tekton/tufcli-cli-stack-push.yaml".pathChanged() ||
        "go.mod".pathChanged() ||
        "go.sum".pathChanged() ||
        "main.go".pathChanged() ||
        "cmd/***".pathChanged() ||
        "internal/***".pathChanged() ||
        "Build.mak".pathChanged() ||
        "trigger-konflux-builds.txt".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cli-stacks
    appstudio.openshift.io/component: tufcli-cli-stack
    pipelines.appstudio.openshift.io/type: build
  name: tufcli-cli-stack-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.cli-stack.rh
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/securesign/tufcli-cli-stack:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '{"type": "gomod", "path": "."}'
  - name: hermetic
    value: "false"
  - name: build-source-image
    value: "true"
  - name: ALLOW_CROSS_PLATFORM_IMAGES
    value: "true"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-tufcli-cli-stack
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
