apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: ".*.env, .*.yml, .*README.md"
    build.appstudio.openshift.io/repo: https://github.com/securesign/tufcli?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "main" &&
      (
        "Dockerfile.tufcli-init".pathChanged() ||
        ".tekton/tufcli-init-push.yaml".pathChanged() ||
        "go.mod".pathChanged() ||
        "go.sum".pathChanged() ||
        "main.go".pathChanged() ||
        "cmd/***".pathChanged() ||
        "internal/***".pathChanged() ||
        "Makefile".pathChanged() ||
        "rhtas/tuf-repo-init.sh".pathChanged() ||
        "trigger-konflux-builds.txt".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tufcli
    appstudio.openshift.io/component: tufcli-init
    pipelines.appstudio.openshift.io/type: build
  name: tufcli-init-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/tufcli-init:{{revision}}
  - name: dockerfile
    value: Dockerfile.tufcli-init
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: [{"path": ".", "type": "gomod"}]
  - name: go_unit_test
    value: true
  - name: fips-check
    value: "true"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: 'https://github.com/securesign/pipelines.git'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: 'pipelines/docker-build-oci-ta.yaml'
  taskRunTemplate:
    serviceAccountName: build-pipeline-tufcli-init
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
